/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.epsiyaya.projetvideoadmin;

import java.awt.CardLayout;

/**
 *
 * @author Al4r1c
 */
public class testNewFrame extends javax.swing.JFrame {

    /**
     * Creates new form testNewFrame
     */
    public testNewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCard = new javax.swing.JPanel();
        panelConnexion1 = new com.epsiyaya.projetvideoadmin.PanelConnexion();
        panelCategorie1 = new com.epsiyaya.projetvideoadmin.panelCategorie();
        panelFilm1 = new com.epsiyaya.projetvideoadmin.panelFilm();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItem_Film = new javax.swing.JMenuItem();
        menuItem_Categ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        jCard.setName("jCard");
        jCard.setPreferredSize(new java.awt.Dimension(900, 680));
        jCard.setLayout(new java.awt.CardLayout());
        jCard.add(panelConnexion1, "CARTE_CON");
        jCard.add(panelCategorie1, "CARTE_CATEG");
        jCard.add(panelFilm1, "CARTE_FILM");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 20));

        jMenu1.setText("Gestion");

        menuItem_Film.setText("Film");
        menuItem_Film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_FilmActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_Film);

        menuItem_Categ.setText("Categorie");
        menuItem_Categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_CategActionPerformed(evt);
            }
        });
        jMenu1.add(menuItem_Categ);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, 1303, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_FilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_FilmActionPerformed
        CardLayout cl = (CardLayout) (jCard.getLayout());
        cl.show(jCard, "CARTE_FILM");
    }//GEN-LAST:event_menuItem_FilmActionPerformed

    private void menuItem_CategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_CategActionPerformed
        CardLayout cl = (CardLayout) (jCard.getLayout());
        cl.show(jCard, "CARTE_CATEG");
    }//GEN-LAST:event_menuItem_CategActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testNewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new testNewFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jCard;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItem_Categ;
    private javax.swing.JMenuItem menuItem_Film;
    private com.epsiyaya.projetvideoadmin.panelCategorie panelCategorie1;
    private com.epsiyaya.projetvideoadmin.PanelConnexion panelConnexion1;
    private com.epsiyaya.projetvideoadmin.panelFilm panelFilm1;
    // End of variables declaration//GEN-END:variables
}
